### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=10002): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000206089E7B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

### ISSUE THREAD

**Issue by bit-scientist** [tae898/age-gender#19]
I am following [Running a client](https://github.com/tae898/age-gender#running-a-client). There I ran two docker containers both for cuda:
1. `docker run --gpus all -it --rm -p 10002:10002 tae898/face-detection-recognition-cuda`
2. `docker run -it --rm -p 10003:10003 --gpus all tae898/age-gender-cuda`

Then I ran `python client.py --mode image --image-path test-images/gettyimages-1067881118-2048x2048.jpg`  and got this error:

```
2023-08-18 10:01:27.469 INFO client - <module>: arguments given to client.py: {'url_face': 'http://127.0.0.1:10002/', 'url_age_gender': 'http://127.0.0.1:10003/', 'image_path': 'test-images/gettyimages-1067881118-2048x2048.jpg', 'camera_id': 0, 'mode': 'image'}
2023-08-18 10:01:27.470 DEBUG client - run_image: loading image ...
2023-08-18 10:01:27.471 INFO client - send_to_servers: image loaded!
2023-08-18 10:01:27.471 DEBUG client - send_to_servers: sending image to server...
2023-08-18 10:01:27.481 DEBUG connectionpool - _new_conn: Starting new HTTP connection (1): 127.0.0.1:10002
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\urllib3\connection.py", line 395, in request
    self.endheaders()
  File "C:\Users\user\anaconda3\envs\age-gender\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\user\anaconda3\envs\age-gender\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "C:\Users\user\anaconda3\envs\age-gender\lib\http\client.py", line 951, in send
    self.connect()
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\urllib3\connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\urllib3\connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001DCE0727B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=10002): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DCE0727B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client.py", line 249, in <module>
    run_image(**args)
  File "client.py", line 153, in run_image
    genders, ages, bboxes, det_scores, landmarks, embeddings = send_to_servers(
  File "client.py", line 40, in send_to_servers
    response = requests.post(url_face, json=data)
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\user\anaconda3\envs\age-gender\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=10002): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DCE0727B80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
```

By the message I can see that the target machine is refusing to connect and that is due to port being already allocated. (am I right?)

However, neither `port=10002` nor `port=10003` is used by other container at this time.
Removing images and restarting docker desktop didn't help. 
After removig the images, running `docker run --gpus all -it --rm -p 10002:10002 tae898/face-detection-recognition-cuda` is now  throwing: 
`docker: Error response from daemon: driver failed programming external connectivity on endpoint nostalgic_robinson (ed79e259cfaf81dcdf29081fb82772cf4290266c9eb1bd30bccbb6295255d322): Bind for 0.0.0.0:10002 failed: port is already allocated.` 
althought `docker container ls` has no active running containers.

Could you help me figure out what's going on, @tae898 ?

**Comment by tae898** [comment]
I just tried on my local Ubuntu machine and it works fine. I see that you are using Windows. Getting things to work on Windows is always tricky. Perhaps [this post](https://github.com/Lawouach/WebSocket-for-Python/issues/130) helps you.
