### ISSUE TITLE
Cant pull docker image 

### ISSUE THREAD

**Issue by RyuShai** [tae898/age-gender#9]
I'm try to re-train follow README but when run command:

`python3 -c "from utils.scripts import extract_Adience_arcface; extract_Adience_arcface('aligned', docker_port=10002, cuda=False, resize=640)"

i got error not found image:

`
ryu@ryu-B450-AORUS-PRO:~/Software/age-gender$ python3 -c "from utils.scripts import extract_Adience_arcface; extract_Adience_arcface('aligned', docker_port=10002, cuda=False, resize=640)"
Unable to find image 'face-detection-recognition' locally
Using default tag: latest
Error response from daemon: pull access denied for face-detection-recognition, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Traceback (most recent call last):
  File "/home/ryu/.local/lib/python3.10/site-packages/python_on_whales/components/image/cli_wrapper.py", line 577, in _pull_if_necessary
    return self.inspect(image)
  File "/home/ryu/.local/lib/python3.10/site-packages/python_on_whales/components/image/cli_wrapper.py", line 257, in inspect
    return Image(self.client_config, x)
  File "/home/ryu/.local/lib/python3.10/site-packages/python_on_whales/components/image/cli_wrapper.py", line 35, in __init__
    super().__init__(client_config, "id", reference, is_immutable_id)
  File "/home/ryu/.local/lib/python3.10/site-packages/python_on_whales/client_config.py", line 187, in __init__
    self._fetch_and_parse_inspect_result(reference_or_id)
  File "/home/ryu/.local/lib/python3.10/site-packages/python_on_whales/client_config.py", line 242, in _fetch_and_parse_inspect_result
    json_str = self._fetch_inspect_result_json(reference)
  File "/home/ryu/.local/lib/python3.10/site-packages/python_on_whales/components/image/cli_wrapper.py", line 44, in _fetch_inspect_result_json
    return run(self.docker_cmd + ["image", "inspect", reference])
  File "/home/ryu/.local/lib/python3.10/site-packages/python_on_whales/utils.py", line 139, in run
    raise NoSuchImage(
python_on_whales.exceptions.NoSuchImage: The docker command executed was `/usr/bin/docker image inspect face-detection-recognition`.
It returned with code 1
The content of stdout is '[]
'
The content of stderr is 'Error: No such image: face-detection-recognition

`

is there any wrong i did ?

**Comment by tae898** [comment]
Hey,

you should be running the docker image before the command.

For the CPU model
```
docker run tae898/face-detection-recognition
```

For the GPU model
```
docker run tae898/face-detection-recognition-cuda
```

**Comment by RyuShai** [comment]
> Hey I fixed the issue. It should work now. Can you give it a try?

It worked, i forgot close issue, so sorry

anw,
I'm trying convert this model to onnx with 
`torch.onnx.export()`
and struck at sample input 

`# create a dummy input tensor  
    dummy_input = torch.randn(1, 512, requires_grad=True)  `
can you help me correct create dummy input for gender.pth model ?

**Comment by tae898** [comment]
>It worked, i forgot close issue, so sorry
nice!

>can you help me correct create dummy input for gender.pth model ?
Is this happening while you are trying to do the onnx thing? cuz I don't have experience in onnx.
